"""initial schema

Revision ID: 380a7d3dd7bf
Revises: 
Create Date: 2026-08-16 16:15:15.047486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '380a7d3dd7bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('alliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alliance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alliance_founder_id'), ['founder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alliance_name'), ['name'], unique=True)

    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('founded_at', sa.DateTime(), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(), nullable=False),
    sa.Column('wood', sa.Float(), nullable=False),
    sa.Column('stone', sa.Float(), nullable=False),
    sa.Column('silver', sa.Float(), nullable=False),
    sa.Column('forum_level', sa.Integer(), nullable=False),
    sa.Column('timber_camp_level', sa.Integer(), nullable=False),
    sa.Column('quarry_level', sa.Integer(), nullable=False),
    sa.Column('silver_mine_level', sa.Integer(), nullable=False),
    sa.Column('farm_level', sa.Integer(), nullable=False),
    sa.Column('barracks_level', sa.Integer(), nullable=False),
    sa.Column('harbour_level', sa.Integer(), nullable=False),
    sa.Column('academy_level', sa.Integer(), nullable=False),
    sa.Column('loyalty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_user_id'), ['user_id'], unique=False)

    op.create_table('alliancemembership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alliancemembership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alliancemembership_alliance_id'), ['alliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alliancemembership_user_id'), ['user_id'], unique=True)

    op.create_table('buildjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('building', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completes_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildjob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildjob_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildjob_completes_at'), ['completes_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildjob_status'), ['status'], unique=False)

    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archetype', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_city_id'), ['city_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_alliance_id'), ['alliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_id'), ['user_id'], unique=False)

    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=False),
    sa.Column('target_x', sa.Integer(), nullable=False),
    sa.Column('target_y', sa.Integer(), nullable=False),
    sa.Column('target_city_id', sa.Integer(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('departs_at', sa.DateTime(), nullable=False),
    sa.Column('arrives_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['target_city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_arrives_at'), ['arrives_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_origin_city_id'), ['origin_city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_target_city_id'), ['target_city_id'], unique=False)

    op.create_table('recruitjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completes_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruitjob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruitjob_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruitjob_completes_at'), ['completes_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruitjob_status'), ['status'], unique=False)

    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('tech', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_city_id'), ['city_id'], unique=False)

    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_city_id'), ['city_id'], unique=False)

    op.create_table('battlereport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('attacker_user_id', sa.Integer(), nullable=False),
    sa.Column('defender_user_id', sa.Integer(), nullable=False),
    sa.Column('attacker_city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('defender_city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attacker_sent', sa.JSON(), nullable=True),
    sa.Column('attacker_survivors', sa.JSON(), nullable=True),
    sa.Column('defender_before', sa.JSON(), nullable=True),
    sa.Column('defender_survivors', sa.JSON(), nullable=True),
    sa.Column('loyalty_before', sa.Integer(), nullable=False),
    sa.Column('loyalty_after', sa.Integer(), nullable=False),
    sa.Column('captured', sa.Boolean(), nullable=False),
    sa.Column('night_bonus', sa.Boolean(), nullable=False),
    sa.Column('naval', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battlereport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battlereport_attacker_user_id'), ['attacker_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battlereport_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_battlereport_defender_user_id'), ['defender_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battlereport_movement_id'), ['movement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battlereport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battlereport_movement_id'))
        batch_op.drop_index(batch_op.f('ix_battlereport_defender_user_id'))
        batch_op.drop_index(batch_op.f('ix_battlereport_created_at'))
        batch_op.drop_index(batch_op.f('ix_battlereport_attacker_user_id'))

    op.drop_table('battlereport')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_city_id'))

    op.drop_table('unit')
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_city_id'))

    op.drop_table('research')
    with op.batch_alter_table('recruitjob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruitjob_status'))
        batch_op.drop_index(batch_op.f('ix_recruitjob_completes_at'))
        batch_op.drop_index(batch_op.f('ix_recruitjob_city_id'))

    op.drop_table('recruitjob')
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_target_city_id'))
        batch_op.drop_index(batch_op.f('ix_movement_status'))
        batch_op.drop_index(batch_op.f('ix_movement_origin_city_id'))
        batch_op.drop_index(batch_op.f('ix_movement_arrives_at'))

    op.drop_table('movement')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_alliance_id'))

    op.drop_table('message')
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_city_id'))

    op.drop_table('hero')
    with op.batch_alter_table('buildjob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildjob_status'))
        batch_op.drop_index(batch_op.f('ix_buildjob_completes_at'))
        batch_op.drop_index(batch_op.f('ix_buildjob_city_id'))

    op.drop_table('buildjob')
    with op.batch_alter_table('alliancemembership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alliancemembership_user_id'))
        batch_op.drop_index(batch_op.f('ix_alliancemembership_alliance_id'))

    op.drop_table('alliancemembership')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_user_id'))

    op.drop_table('city')
    with op.batch_alter_table('alliance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alliance_name'))
        batch_op.drop_index(batch_op.f('ix_alliance_founder_id'))

    op.drop_table('alliance')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
