import "./env";
import { eq, inArray } from "drizzle-orm";
import { db, sql } from "@/db";
import { exercises, programDays, programExercises, programWeeks, programs } from "@/db/schema";
import { resolveExerciseName } from "@/lib/exerciseResolver";

/**
 * Rebuilds "Creeping Death III" — with an important caveat this entry has to
 * carry that Creeping Death II did not.
 *
 * Mountain Dog Diet's actual program catalogue (mountaindogdiet.com/programs/)
 * lists "Creeping Death" and "Creeping Death 2". There is no "Creeping Death
 * 3" anywhere in it, on JeFit, or anywhere else searched. This title was very
 * likely invented at generation time — the model extrapolating a sequel that
 * doesn't exist, the same way it mistook a leg-day finisher for Creeping
 * Death II's whole program.
 *
 * The old version (1 day/week, 6 weeks, 8 sets) was wrong on top of that
 * shaky premise. Deleting the program outright is also an option, but this
 * follows the app's standing rule — label honestly rather than remove —
 * with `confidence: "stylistic"` and notes that say plainly the title itself
 * is unconfirmed. Reuses the real, sourced Creeping Death II structure (see
 * fix-creeping-death-2.ts) as the stylistic basis, since a genuine "further
 * evolution" of the confirmed program is the most honest thing to offer
 * under this name.
 */

type Ex = { name: string; sets: number; reps: string; notes?: string };
type Day = { name: string; exercises: Ex[] };

const WEEK: Day[] = [
  {
    name: "Pull",
    exercises: [
      { name: "Meadows Row", sets: 4, reps: "10" },
      { name: "Chin-Up", sets: 4, reps: "8", notes: "Weighted if available." },
      { name: "Rack Pull", sets: 5, reps: "5" },
      { name: "Dumbbell Pullover", sets: 3, reps: "10" },
      { name: "Back Extension", sets: 3, reps: "12", notes: "Loaded." },
      { name: "EZ-Bar Curl", sets: 4, reps: "8" },
      { name: "Hammer Curl", sets: 4, reps: "10" },
    ],
  },
  {
    name: "Push",
    exercises: [
      { name: "Incline Barbell Bench Press", sets: 4, reps: "6" },
      { name: "Incline Dumbbell Press", sets: 3, reps: "10" },
      { name: "Machine Chest Press", sets: 3, reps: "8" },
      { name: "Cable Fly", sets: 3, reps: "10" },
      { name: "Cable Rear Delt Fly", sets: 4, reps: "15" },
      { name: "Weighted Chest Dip", sets: 4, reps: "AMRAP" },
      { name: "EZ-Bar Skull Crusher", sets: 4, reps: "12", notes: "Reverse grip." },
    ],
  },
  {
    name: "Legs",
    exercises: [
      { name: "Back Squat", sets: 5, reps: "6", notes: "Full depth." },
      { name: "Seated Leg Curl", sets: 4, reps: "10" },
      { name: "Bulgarian Split Squat", sets: 4, reps: "8", notes: "Drop sets." },
      { name: "Stiff-Leg Deadlift", sets: 3, reps: "10" },
      { name: "Standing Calf Raise", sets: 6, reps: "10" },
    ],
  },
  {
    name: "Pull (Pump)",
    exercises: [
      { name: "Seated Cable Row", sets: 4, reps: "12" },
      { name: "Reverse-Grip Lat Pulldown", sets: 4, reps: "10" },
      { name: "Face Pull", sets: 4, reps: "12" },
      { name: "Dumbbell Pullover", sets: 4, reps: "10" },
      { name: "Cross-Body Hammer Curl", sets: 4, reps: "10" },
      { name: "Barbell Curl", sets: 3, reps: "21", notes: "\"21s\" technique." },
      { name: "Cable Crunch", sets: 4, reps: "20" },
    ],
  },
  {
    name: "Push (Pump)",
    exercises: [
      { name: "Decline Dumbbell Press", sets: 4, reps: "12" },
      { name: "Floor Press", sets: 4, reps: "10", notes: "Performed with dumbbells." },
      { name: "Cable Fly", sets: 4, reps: "10" },
      { name: "Dumbbell Lateral Raise", sets: 4, reps: "15" },
      { name: "Seated Dumbbell Shoulder Press", sets: 4, reps: "10" },
      { name: "Rope Pushdown", sets: 4, reps: "10" },
      { name: "Overhead Cable Triceps Extension", sets: 4, reps: "12" },
    ],
  },
  {
    name: "Legs (Pump)",
    exercises: [
      { name: "Leg Extension", sets: 3, reps: "15" },
      { name: "Leg Press", sets: 3, reps: "15" },
      { name: "Walking Lunge", sets: 3, reps: "10" },
      { name: "Seated Leg Curl", sets: 3, reps: "15" },
      { name: "Seated Calf Raise", sets: 6, reps: "15" },
    ],
  },
];

const CONFIDENCE_NOTES = `Important caveat this entry needs to carry, in plain terms: I could not confirm "Creeping Death III" is a real, separately published John Meadows / Mountain Dog Diet program. Mountain Dog Diet's own program catalogue (mountaindogdiet.com/programs/) lists "Creeping Death" and "Creeping Death 2" — no "3" appears there, on JeFit, or anywhere else checked. It's likely this title was generated by extrapolating a sequel that doesn't actually exist.

Rather than remove the entry, it's rebuilt here in the confirmed style of Creeping Death II — the same real 6-day Pull/Push/Legs structure with alternating base and pump days, which is well documented — but nothing about this specific week's exercise selection should be taken as a transcript of a real "Creeping Death III." Treat this as a plausible continuation in Meadows' style, not a sourced program. If you're looking for the real thing, Creeping Death and Creeping Death 2 are the two that actually exist.`;

async function resolveAll(days: Day[]): Promise<Map<string, number>> {
  const names = new Set<string>();
  for (const day of days) for (const ex of day.exercises) names.add(ex.name);
  const resolved = new Map<string, number>();
  for (const name of names) {
    const r = await resolveExerciseName(name);
    if (!r) throw new Error(`"${name}" did not resolve against the catalogue`);
    resolved.set(name, r.id);
  }
  return resolved;
}

async function main() {
  const [program] = await db
    .select({ id: programs.id })
    .from(programs)
    .where(eq(programs.slug, "meadows-creeping-death-3"));
  if (!program) throw new Error("meadows-creeping-death-3 not found");

  console.log("resolving exercises...");
  const exerciseIds = await resolveAll(WEEK);
  console.log(`resolved ${exerciseIds.size} exercises.`);

  await db.transaction(async (tx) => {
    await tx.delete(programWeeks).where(eq(programWeeks.programId, program.id));

    await tx
      .update(programs)
      .set({
        daysPerWeek: 6,
        weeks: 12,
        splitType: "6-day Pull/Push/Legs with alternating base and pump days (unconfirmed sequel)",
        summary:
          "A stylistic continuation of John Meadows' Creeping Death lineage — the same 6-day Pull/Push/Legs structure as the confirmed Creeping Death II. \"Creeping Death III\" itself could not be confirmed as a real, separately published program.",
        description:
          "Built in the same confirmed structure as Creeping Death II (6 days a week, alternating heavier \"base\" sessions with higher-rep \"pump\" sessions across Pull, Push, and Legs), since a search of Mountain Dog Diet's own catalogue and other sources found no evidence \"Creeping Death III\" was ever actually released. Treat this as a plausible, honestly-labeled extrapolation in Meadows' style — not a transcript of a real numbered sequel.",
        confidence: "stylistic",
        confidenceNotes: CONFIDENCE_NOTES,
        verified: false,
        sourceUrls: [
          "https://mountaindogdiet.com/programs/creeping-death-2/",
          "https://www.jefit.com/routines/468549/creeping-death-by-meadows",
        ],
      })
      .where(eq(programs.id, program.id));

    const [week] = await tx
      .insert(programWeeks)
      .values({ programId: program.id, weekNumber: 1, repeatCount: 1 })
      .returning({ id: programWeeks.id });

    for (const [dayIndex, day] of WEEK.entries()) {
      const [savedDay] = await tx
        .insert(programDays)
        .values({ weekId: week.id, dayIndex, name: day.name })
        .returning({ id: programDays.id });

      for (const [order, ex] of day.exercises.entries()) {
        await tx.insert(programExercises).values({
          dayId: savedDay.id,
          exerciseId: exerciseIds.get(ex.name)!,
          order,
          sets: ex.sets,
          reps: ex.reps,
          intensityType: "none",
          notes: ex.notes ?? null,
        });
      }
    }
  });

  // Recompute equipmentRequired from the corrected exercise list.
  const usedIds = await db
    .selectDistinct({ exerciseId: programExercises.exerciseId })
    .from(programExercises)
    .innerJoin(programDays, eq(programDays.id, programExercises.dayId))
    .innerJoin(programWeeks, eq(programWeeks.id, programDays.weekId))
    .where(eq(programWeeks.programId, program.id));
  const equipRows = await db
    .select({ equipment: exercises.equipment })
    .from(exercises)
    .where(inArray(exercises.id, usedIds.map((r) => r.exerciseId)));
  const equipmentRequired = [...new Set(equipRows.map((r) => r.equipment))];
  await db.update(programs).set({ equipmentRequired }).where(eq(programs.id, program.id));

  const [check] = await db
    .select({ daysPerWeek: programs.daysPerWeek, weeks: programs.weeks, confidence: programs.confidence })
    .from(programs)
    .where(eq(programs.id, program.id));
  console.log("done:", check, "equipment:", equipmentRequired);
  await sql.end();
}

main().catch(async (err) => {
  console.error(err);
  await sql.end();
  process.exit(1);
});
