import "./env";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import Anthropic from "@anthropic-ai/sdk";
import { parseExerciseRows, type ParsedExercise } from "@/data/parseExercises";
import { EXERCISE_DESCRIPTIONS } from "@/data/exerciseDescriptions";
import {
  batchDescriptionJsonSchema,
  batchDescriptionSchema,
} from "@/lib/exerciseDescriptionSchema";

/**
 * Writes how-to-perform text for every exercise in the catalogue that
 * doesn't already have one.
 *
 *   npm run generate:exercise-descriptions -- --dry-run --limit 5
 *   npm run generate:exercise-descriptions -- --only squat
 *   npm run generate:exercise-descriptions                       # everything missing
 *
 * Resumable by design, same as generate-batch.ts: anything already in
 * src/data/exerciseDescriptions.ts is skipped, and the file is rewritten
 * after every batch (not just at the end), so an interrupted or
 * credit-exhausted run costs nothing to restart — just re-run it.
 *
 * One request describes a batch of exercises rather than one each, both to
 * keep the request count down and because the model writes more consistent,
 * differentiated cueing when it can see related movements together.
 */

const DEFAULT_MODEL = "claude-sonnet-5";
const BATCH_SIZE = 12;
const MAX_TOKENS = 8000;
const OUT_FILE = join(import.meta.dirname, "../src/data/exerciseDescriptions.ts");

const SYSTEM = `You are a strength coach writing exercise-library entries for a training app.

For each exercise, write:
1. One short paragraph (2-4 sentences) on what the movement is and what it trains.
2. A blank line, then 3-5 bullet-point form cues, each starting with "- ".

Rules:
- Plain, descriptive coaching language. Say how the movement is performed and what good execution looks like — stance, grip, range of motion, what to brace, common technique faults to avoid.
- Do not give medical, injury-treatment, or rehabilitation advice, and do not claim this replaces in-person coaching.
- Do not repeat the exercise's name as the first word of the paragraph in a robotic way ("The Barbell Back Squat is...") for every entry — vary the opening.
- Base the cues on the exercise's actual pattern, muscles, and equipment as given; do not invent equipment it doesn't use.
- Return every exercise you were given, in the same order, using its exact slug.`;

function flag(args: string[], name: string): string | undefined {
  const value = args[args.indexOf(name) + 1];
  return value && !value.startsWith("--") ? value : undefined;
}

function catalogueLine(e: ParsedExercise): string {
  const bits = [
    e.movementPattern.replace(/_/g, " "),
    `primary: ${e.primaryMuscle.replace(/_/g, " ")}`,
    e.secondaryMuscles.length &&
      `secondary: ${e.secondaryMuscles.map((m) => m.replace(/_/g, " ")).join(", ")}`,
    `equipment: ${e.equipment}`,
    e.isUnilateral && "unilateral",
    e.isCompound ? "compound" : "isolation",
    e.isExplosive && "explosive",
  ].filter(Boolean);
  return `${e.slug} — ${e.name} (${bits.join("; ")})`;
}

function writeDescriptions(map: Record<string, string>) {
  const entries = Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug, desc]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(desc)},`)
    .join("\n");

  const lines = [
    "/**",
    " * How to perform each exercise and what good form looks like, keyed by slug.",
    " *",
    " * A separate file from exercises.ts rather than an 8th pipe column there: the",
    " * pipe-delimited catalogue has no way to escape a `|` or a newline, and these",
    " * run 500-900 characters of prose each — cramming that into the catalogue's",
    " * one-line-per-exercise format would destroy the scannability its own doc",
    " * comment exists to protect.",
    " *",
    " * Generated by `npm run generate:exercise-descriptions` (see",
    " * scripts/generate-exercise-descriptions.ts), which is resumable and writes",
    " * this file back after every batch — re-running it only fills in whatever's",
    " * still missing. `npm run seed:exercises` merges these into the `exercises`",
    " * table's `description` column.",
    " *",
    " * General training guidance, not medical advice.",
    " */",
    "export const EXERCISE_DESCRIPTIONS: Record<string, string> = {",
    entries,
    "};",
    "",
  ];
  writeFileSync(OUT_FILE, lines.join("\n"));
}

async function describeBatch(
  batch: ParsedExercise[],
  model: string,
): Promise<Map<string, string>> {
  const client = new Anthropic();

  const stream = client.messages.stream({
    model,
    max_tokens: MAX_TOKENS,
    system: SYSTEM,
    output_config: {
      format: { type: "json_schema", schema: batchDescriptionJsonSchema() },
    },
    messages: [
      {
        role: "user",
        content: `Write entries for these ${batch.length} exercises:\n\n${batch.map(catalogueLine).join("\n")}`,
      },
    ],
  });

  const message = await stream.finalMessage();

  if (message.stop_reason === "refusal") {
    throw new Error(
      `model declined: ${message.stop_details?.explanation ?? "no explanation"}`,
    );
  }
  if (message.stop_reason === "max_tokens") {
    throw new Error(`output hit max_tokens (${MAX_TOKENS}) — lower BATCH_SIZE`);
  }

  const text = message.content.find((b) => b.type === "text");
  if (!text || text.type !== "text") throw new Error("no text block in response");

  const parsed = batchDescriptionSchema.parse(JSON.parse(text.text));
  return new Map(parsed.exercises.map((e) => [e.slug, e.description]));
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const force = args.includes("--force");
  const model = flag(args, "--model") ?? DEFAULT_MODEL;
  const only = flag(args, "--only");
  const limit = Number(flag(args, "--limit") ?? Number.POSITIVE_INFINITY);

  const all = parseExerciseRows();
  let queue = only
    ? all.filter(
        (e) =>
          e.slug.includes(only) || e.name.toLowerCase().includes(only.toLowerCase()),
      )
    : all;

  const have = new Set(Object.keys(EXERCISE_DESCRIPTIONS));
  if (!force) {
    const before = queue.length;
    queue = queue.filter((e) => !have.has(e.slug));
    if (before !== queue.length) {
      console.log(
        `skipping ${before - queue.length} already described (--force to redo)`,
      );
    }
  }

  if (queue.length > limit) {
    console.log(`limiting to ${limit} of ${queue.length} queued`);
    queue = queue.slice(0, limit);
  }

  if (queue.length === 0) {
    console.log("nothing to do — every exercise already has a description");
    return;
  }

  console.log(
    `describing ${queue.length} exercise(s) in batches of ${BATCH_SIZE} with ${model}${dryRun ? " (dry run)" : ""}\n`,
  );

  const result = { ...EXERCISE_DESCRIPTIONS };
  let done = 0;

  for (let i = 0; i < queue.length; i += BATCH_SIZE) {
    const batch = queue.slice(i, i + BATCH_SIZE);
    console.log(`[batch ${Math.floor(i / BATCH_SIZE) + 1}] ${batch.map((e) => e.slug).join(", ")}`);

    const described = await describeBatch(batch, model);

    for (const e of batch) {
      const text = described.get(e.slug);
      if (!text) {
        console.log(`    ✗ missing "${e.slug}" in the model's response`);
        continue;
      }
      console.log(`    ✓ ${e.slug} (${text.length} chars)`);
      if (!dryRun) result[e.slug] = text;
      done++;
    }

    // Written after every batch, not just at the end, so a crash or a
    // credit-exhausted run mid-way keeps everything completed so far.
    if (!dryRun) writeDescriptions(result);
  }

  console.log(`\n${done} of ${queue.length} described${dryRun ? " (not saved — dry run)" : ""}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
